seekingalpha/javascript

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-react/package.json, eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-flowtype/index.js, eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-jest/index.js, eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-jsx-a11y/index.js, eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-react/jsx.js
- [deps] update `eslint-config-seekingalpha-base` to version 1.6.0
- [new] `flowtype/require-compound-type-alias` rule error with `never` option
- [new] `jest/consistent-test-it` rule error
- [new] `jest/expect-expect` rule error
- [new] `jest/no-jasmine-globals` rule error
- [new] `jest/no-jest-import` rule error
- [new] `jest/no-large-snapshots` rule error with `maxSize: 50` option
- [new] `jest/no-test-prefixes` rule error
- [new] `jest/no-test-return-statement` rule error
- [new] `jest/prefer-strict-equal` rule error
- [new] `jest/prefer-to-be-null` rule error
- [new] `jest/prefer-to-be-undefined` rule error
- [new] `jest/valid-describe` rule error
- [new] `jest/valid-expect` rule error
- [new] `jest/valid-expect-in-promise` rule error
- [new] `jsx-a11y/label-has-associated-control` …
=> eslint-config-seekingalpha-react version 1.4.0

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-react/README.md, eslint-configs/eslint-config-seekingalpha-react/package.json, eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-flowtype/index.js
- [deps] upgrade `eslint-plugin-flowtype` to version 3.10.3
- [new] `flowtype/delimiter-dangle` enable with 'always' option
=> eslint-config-seekingalpha-react ver. 2.6.0

eslint-configs/eslint-config-seekingalpha-qa/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-qa/package.json, eslint-configs/eslint-config-seekingalpha-qa/rules/eslint-plugin-mocha/index.js
- [breaking] `mocha/valid-suite-description` updated validation regex to be `^[A-Z]\\d+: should`
=> eslint-config-seekingalpha-qa ver. 1.1.0

eslint-configs/eslint-config-seekingalpha-qa/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-qa/package.json, eslint-configs/eslint-config-seekingalpha-qa/rules/eslint-plugin-mocha/index.js
- [breaking] revert `mocha/valid-suite-description` validation regex to `^[A-Z]`
- [breaking] `mocha/valid-test-description` updated validation regex to be `^[A-Z]\\d+: should`
=> eslint-config-seekingalpha-qa ver. 1.2.0

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-react/README.md, eslint-configs/eslint-config-seekingalpha-react/package.json, eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-react/jsx.js
- [deps] upgrade `eslint-plugin-jest` to version 22.15.1
- [patch: loosen rules] `react/jsx-no-binde` enable `ignoreDOMComponents` option
=> eslint-config-seekingalpha-react ver. 3.1.0

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-base/README.md, eslint-configs/eslint-config-seekingalpha-base/package.json, eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-unicorn/index.js, eslint-configs/eslint-config-seekingalpha-base/rules/eslint/best-practices.js
- [deps] update `eslint-plugin-unicorn` to version `25.0.1`
- [breaking] enable `require-unicode-regexp` rule
- [breaking] enable `unicorn/consistent-destructuring` rule
- [breaking] enable `unicorn/no-new-array` rule
- [breaking] enable `unicorn/prefer-array-index-of` rule
- [breaking] enable `unicorn/prefer-regexp-test` rule
=> eslint-config-seekingalpha-base ver. 4.26.0

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-base/README.md, eslint-configs/eslint-config-seekingalpha-base/package.json, eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-import/module-systems.js, eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-import/static-analysis.js
- [deps] update `eslint-plugin-import` to version `2.23.2`
- [breaking] enable `import/no-import-module-exports` rule
=> eslint-config-seekingalpha-base ver. 4.45.0

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-react/package.json, eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-jest/index.js
- [breaking] set `jest/max-nested-describe` rule to `2`
=> eslint-config-seekingalpha-react ver. 4.71.0

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-react/package.json, eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-react/jsx.js
[deps] disable `react/jsx-handler-names` rule
The rule works only for the object methods which makes it outdated in our current codebase since most of the components are functional. If we enable it for functional components, we'd have over 1000 errors for this rule which indicates how much we need this rule.
=> eslint-config-seekingalpha-react ver. 4.72.0

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-react/package.json, eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-jest/index.js
- [patch] fixed `jest/no-restricted-matchers` rule according to `jest/prefer-expect-resolves`
=> eslint-config-seekingalpha-react ver. 4.80.0

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-react/README.md, eslint-configs/eslint-config-seekingalpha-react/package.json, eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-jsx-a11y/index.js
- [deps] upgrade `eslint-plugin-jsx-a11y` to version `6.5.1`
- [breaking] removed deprecated `jsx-a11y/accessible-emoji` rule
=> eslint-config-seekingalpha-react ver. 4.91.0

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-base/README.md, eslint-configs/eslint-config-seekingalpha-base/package.json
- [deps] revert `eslint-plugin-import` to version `2.25.3`
=> eslint-config-seekingalpha-base ver. 5.2.1

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-react/README.md, eslint-configs/eslint-config-seekingalpha-react/package.json
- [deps] upgrade `eslint-plugin-react-hooks` to version `4.6.0`
=> eslint-config-seekingalpha-react ver. 5.21.0

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-tests/package.json, eslint-configs/eslint-config-seekingalpha-tests/rules/eslint-plugin-testing-library/index.js
- [breaking] update `testing-library/no-await-sync-events` rule
=> eslint-config-seekingalpha-tests ver. 1.22.0

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-tests/README.md, eslint-configs/eslint-config-seekingalpha-tests/package.json, eslint-configs/eslint-config-seekingalpha-tests/rules/eslint-plugin-jest/index.js
- [deps] upgrade `eslint-plugin-jest` to version `26.7.0`
- [deps] upgrade `eslint-plugin-testing-library` to version `5.6.0`
- [breaking] enable `jest/prefer-mock-promise-shorthand` rule
=> eslint-config-seekingalpha-tests ver. 1.26.0

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-tests/README.md, eslint-configs/eslint-config-seekingalpha-tests/package.json, eslint-configs/eslint-config-seekingalpha-tests/rules/eslint-plugin-jest/index.js
- [deps] upgrade `eslint-plugin-jest` to version `27.0.1`
- [breaking] enable `jest/no-jest-import` rule
=> eslint-config-seekingalpha-tests ver. 1.36.0

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-base/package.json, eslint-configs/eslint-config-seekingalpha-base/rules/eslint/layout-and-formatting.js
- [breaking] `lines-around-comment` rule - ignore `@ts-expect-error` comments
=> eslint-config-seekingalpha-base ver. 5.38.0

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-typescript/package.json, eslint-configs/eslint-config-seekingalpha-typescript/rules/config.js, eslint-configs/eslint-config-seekingalpha-typescript/rules/typescript-eslint/index.js
- [breaking] relax `@typescript-eslint/no-magic-numbers` rule for types
=> eslint-config-seekingalpha-typescript ver. 1.0.2

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-typescript/package.json, eslint-configs/eslint-config-seekingalpha-typescript/rules/typescript-eslint/index.js
- [breaking] relax `@typescript-eslint/no-magic-numbers` rule for types
=> eslint-config-seekingalpha-typescript

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-typescript/package.json, eslint-configs/eslint-config-seekingalpha-typescript/rules/disable-recommended-eslint-rules/index.js
- [breaking] disable `no-undef` rule
=> eslint-config-seekingalpha-typescript ver. 1.0.4

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-typescript/README.md, eslint-configs/eslint-config-seekingalpha-typescript/package.json, eslint-configs/eslint-config-seekingalpha-typescript/rules/disable-recommended-eslint-rules/index.js, eslint-configs/eslint-config-seekingalpha-typescript/rules/typescript-eslint/index.js
- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.49.0`
- [breaking] enable `@typescript-eslint/key-spacing` rule
=> eslint-config-seekingalpha-typescript ver. 1.12.0

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-typescript/README.md, eslint-configs/eslint-config-seekingalpha-typescript/package.json, eslint-configs/eslint-config-seekingalpha-typescript/rules/disable-recommended-eslint-rules/index.js, eslint-configs/eslint-config-seekingalpha-typescript/rules/typescript-eslint/index.js
- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.55.0`
- [breaking] enable `@typescript-eslint/block-spacing` rule
- [breaking] enable `@typescript-eslint/no-import-type-side-effects` rule
=> eslint-config-seekingalpha-typescript ver. 1.21.0

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-typescript/README.md, eslint-configs/eslint-config-seekingalpha-typescript/package.json, eslint-configs/eslint-config-seekingalpha-typescript/rules/disable-recommended-eslint-rules/index.js, eslint-configs/eslint-config-seekingalpha-typescript/rules/typescript-eslint/index.js
- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.57.0`
- [breaking] enable `@typescript-eslint/no-duplicate-type-constituents` rule
- [breaking] enable `@typescript-eslint/lines-around-comment` rule
=> eslint-config-seekingalpha-typescript ver. 1.23.0

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-typescript/package.json, eslint-configs/eslint-config-seekingalpha-typescript/rules/typescript-eslint/index.js
- [breaking] disable `@typescript-eslint/no-duplicate-type-constituents` rule
=> eslint-config-seekingalpha-typescript ver. 1.23.1

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-tests/package.json, eslint-configs/eslint-config-seekingalpha-tests/rules/eslint-plugin-testing-library/index.js
- [breaking] removed deprecated `testing-library/no-wait-for-empty-callback` rule
=> eslint-config-seekingalpha-tests ver. 1.74.1

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-tests/README.md, eslint-configs/eslint-config-seekingalpha-tests/package.json, eslint-configs/eslint-config-seekingalpha-tests/rules/eslint-plugin-jest/index.js
- [deps] upgrade `eslint-plugin-jest` to version `27.4.0`
- [breaking] enable `jest/no-confusing-set-timeout` rule
=> eslint-config-seekingalpha-tests ver. 1.77.0

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-typescript/README.md, eslint-configs/eslint-config-seekingalpha-typescript/package.json
- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `7.0.2`
- [deps] upgrade `@typescript-eslint/parser` to version `7.0.2`
=> eslint-config-seekingalpha-typescript ver. 4.25.0

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-typescript/package.json, eslint-configs/eslint-config-seekingalpha-typescript/prettier.js, package.json
- [breaking] disable `@stylistic/ts/lines-around-comment` for prettier config
=> eslint-config-seekingalpha-typescript ver. 4.35.0

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-base/package.json, eslint-configs/eslint-config-seekingalpha-base/rules/eslint/suggestions.js
- [breaking] enable `logical-assignment-operators` rule
=> eslint-config-seekingalpha-base ver. 8.2.0

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-base/README.md, eslint-configs/eslint-config-seekingalpha-base/index.js, eslint-configs/eslint-config-seekingalpha-base/package.json, eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-no-use-extend-native/index.js, package.json
- [deps] removed `eslint-plugin-no-use-extend-native`
=> eslint-config-seekingalpha-base ver. 8.3.0

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-typescript/README.md, eslint-configs/eslint-config-seekingalpha-typescript/package.json, eslint-configs/eslint-config-seekingalpha-typescript/rules/typescript-eslint/index.js, package.json
- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `7.16.0`
- [deps] upgrade `@typescript-eslint/parser` to version `7.16.0`
- [breaking] enable `@typescript-eslint/no-empty-object-type` rule
- [breaking] enable `@typescript-eslint/no-unnecessary-parameter-property-assignment` rule
=> eslint-config-seekingalpha-typescript ver. 5.12.0

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md, eslint-configs/eslint-config-seekingalpha-typescript/README.md, eslint-configs/eslint-config-seekingalpha-typescript/package.json, eslint-configs/eslint-config-seekingalpha-typescript/rules/disable-recommended-eslint-rules/index.js, eslint-configs/eslint-config-seekingalpha-typescript/rules/typescript-eslint/index.js, package.json
- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `8.0.0`
- [deps] upgrade `@typescript-eslint/parser` to version `8.0.0`
- [breaking] enable `@typescript-eslint/no-unsafe-function-type` rule
- [breaking] enable `@typescript-eslint/no-wrapper-object-types` rule
=> eslint-config-seekingalpha-typescript ver. 5.16.0
