seekingalpha/javascript

.eslintrc.js
eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/index.js
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-base/rules/eslint/best-practices.js
eslint-configs/eslint-config-seekingalpha-base/rules/parser-options.js

- [major] remove default `env` configuration
- [major] update `parserOptions`
- [pathc] clean React specific methods from `class-methods-use-this` rule

eslint-config-seekingalpha-base ver 1.7.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json

- [deps] update `eslint-plugin-import` to version 2.17.2

eslint-config-seekingalpha-base ver. 2.2.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-import/static-analysis.js
eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-jsdoc/index.js
eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-unicorn/index.js

- [deps] update `eslint-plugin-import` to version 2.17.3
- [deps] update `eslint-plugin-jsdoc` to version 7.2.3
- [deps] update `eslint-plugin-unicorn` to version 9.0.0
- [beaking] enable `import/no-unused-modules` rule
- [beaking] enable `jsdoc/implements-on-classes` rule
- [beaking] enable `jsdoc/match-description` rule
- [beaking] enable `jsdoc/no-types` rule
- [beaking] enable `jsdoc/require-jsdoc` rule
- [beaking] enable `unicorn/prefer-event-key` rule
- [beaking] enable `unicorn/prefer-flat-map` rule

eslint-config-seekingalpha-base ver. 2.3.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json
eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-flowtype/index.js
eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-jest/index.js
eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-react/jsx.js
eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-react/react.js

- [deps] upgrade `eslint-plugin-flowtype` to version 3.10.1
- [deps] upgrade `eslint-plugin-jest` to version 22.6.4
- [deps] upgrade `eslint-plugin-react` to version 7.13.0
- [new] `flowtype/require-parameter-type` rule error
- [new] `flowtype/require-return-type` rule error
- [new] `flowtype/type-id-match` rule error
- [new] `flowtype/type-import-style` rule error
- [new] `flowtype/no-mixed` rule error
- [new] `flowtype/spread-exact-type` rule error
- [new] `flowtype/require-readonly-react-props` rule error
- [new] `jest/no-commented-out-tests` rule error
- [new] `jest/no-mocks-import` rule error
- [new] `react/prefer-read-only-props` rule error
- [new] `react/state-in-constructor` rule error
- [new] `react/boolean-prop-naming` rule error
- [new] `react/static-property-placement` rule …

eslint-config-seekingalpha-react ver. 2.5.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] update `babel-eslint` to version 10.0.3

eslint-config-seekingalpha-react ver. 3.4.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-react` to version `7.21.5`
- [deps] upgrade `eslint-plugin-react-hooks` to version `4.2.0`

eslint-config-seekingalpha-react ver. 4.25.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-unicorn/index.js

- [deps] update `eslint-plugin-unicorn` to version `25.0.0`
- [breaking] enable `unicorn/prefer-array-some` rule
- [breaking] enable `unicorn/prefer-default-parameters` rule
- [breaking] enable `unicorn/prefer-math-trunc` rule

eslint-config-seekingalpha-base ver. 4.23.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json

- [deps] update `eslint-plugin-unicorn` to version `25.0.1`

eslint-config-seekingalpha-base ver. 4.24.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json
eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-react/jsx.js
eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-react/react.js

- [deps] upgrade `eslint-plugin-react` to version `7.22.0`
- [new] `react/jsx-newline` rule error
- [new] `react/jsx-no-constructed-context-values` rule error
- [new] `react/no-adjacent-inline-elements` rule error

eslint-config-seekingalpha-react ver. 4.35.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/package.json
eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-react/react.js
package.json

- [new] `react/function-component-definition` rule error

seekingalpha-javascript-style ver. 4.36.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-unicorn/index.js

- [deps] update `eslint-plugin-unicorn` to version `27.0.0`
- [breaking] enable `unicorn/no-array-push-push` rule
- [breaking] enable `unicorn/no-this-assignment` rule
- [breaking] enable `unicorn/prefer-ternary` rule

eslint-config-seekingalpha-base ver. 4.28.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json

- [deps] update `eslint-plugin-unicorn` to version `28.0.0`

eslint-config-seekingalpha-base ver. 4.30.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json

- [deps] update `eslint-plugin-promise` to version `4.3.1`

eslint-config-seekingalpha-base ver. 4.31.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json

- [deps] update `eslint-plugin-unicorn` to version `28.0.1`

eslint-config-seekingalpha-base ver. 4.33.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-jest` to version `24.1.5`

eslint-config-seekingalpha-react ver. 4.40.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-flowtype` to version `5.2.2`

eslint-config-seekingalpha-react ver. 4.42.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json
eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-flowtype/index.js

- [deps] upgrade `eslint-plugin-flowtype` to version `5.3.0`
- [new] `flowtype/object-type-curly-spacing` rule error

eslint-config-seekingalpha-react ver. 4.43.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/package.json
eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-flowtype/index.js

- [patch: loosen rules] disable `flowtype/object-type-curly-spacing` rule

eslint-config-seekingalpha-react ver. 4.43.1

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-flowtype` to version `5.3.1`
- [new] `flowtype/object-type-curly-spacing` rule error

eslint-config-seekingalpha-react ver. 4.44.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-jest` to version `24.1.9`

eslint-config-seekingalpha-react ver. 4.47.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-jest` to version `24.1.10`

eslint-config-seekingalpha-react ver. 4.48.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-jest` to version `24.2.1`

[TECH] eslint-config-seekingalpha-react ver. 4.49.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-jest` to version `24.3.2`

eslint-config-seekingalpha-react ver. 4.51.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-unicorn/index.js

- [deps] update `eslint-plugin-unicorn` to version `29.0.0`
- [breaking] enable `unicorn/no-static-only-class` rule
- [breaking] enable `unicorn/prefer-array-flat` rule

eslint-config-seekingalpha-base ver. 4.37.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json
eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-react/react.js

- [deps] upgrade `eslint-plugin-react` to version `7.23.1`
- [new] `react/no-unstable-nested-components` rule error

eslint-config-seekingalpha-react ver. 4.52.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/package.json
eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-react/react.js

- [fix] update `react/boolean-prop-naming` rule regexp

eslint-config-seekingalpha-react ver. 4.53.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/package.json
eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-react/react.js

- [fix] revert `react/no-unstable-nested-components` rule error

eslint-config-seekingalpha-react ver. 4.54.1

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-jest` to version `24.3.3`

eslint-config-seekingalpha-react ver. 4.55.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-jest` to version `24.4.0`
- [deps] upgrade `eslint-plugin-flowtype` to version `5.6.0`

eslint-config-seekingalpha-react ver. 4.56.0

---

eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-node/package.json
eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json
eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-flowtype/index.js

- [deps] upgrade `eslint-plugin-flowtype` to version `5.7.1`

eslint-config-seekingalpha-react ver. 4.58.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-unicorn/index.js

- [deps] update `eslint-plugin-unicorn` to version `30.0.0`

eslint-config-seekingalpha-base ver. 4.40.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-jest` to version `24.3.6`

eslint-config-seekingalpha-react ver. 4.60.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json
eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-flowtype/index.js

- [deps] drop direct dependency on `babel-eslint`

[TECH] eslint-config-seekingalpha-react

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-base/rules/eslint/stylistic-issues.js

- [patch] update `comma-dangle` rule

eslint-config-seekingalpha-base ver. 4.42.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-import/module-systems.js

- [breaking] disable `import/no-import-module-exports` rule

eslint-config-seekingalpha-base ver. 4.46.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] revert `eslint-plugin-react` to version `7.22.0`

eslint-config-seekingalpha-react ver. 4.63.1

---

eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-import/style-guide.js
eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] patch `import/order` rule

eslint-config-seekingalpha-react ver. 4.64.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] patch `import/order` rule

eslint-config-seekingalpha-base ver. 4.48.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json
eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-jest/index.js

- [deps] upgrade `eslint-plugin-jest` to version `24.4.0`
- [deps] upgrade `eslint-plugin-flowtype` to version `5.8.1`
- [breaking] enable `jest/max-nested-describe` rule

eslint-config-seekingalpha-react ver. 4.70.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-unicorn/index.js

- [breaking] disable `unicorn/prefer-object-from-entries` rule

eslint-config-seekingalpha-base ver. 4.55.1

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-import/style-guide.js

- [deps] update `eslint-plugin-import` to version `2.24.0`

eslint-config-seekingalpha-base ver. 4.56.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json

- [deps] update `eslint-plugin-import` to version `2.24.1`

eslint-config-seekingalpha-base ver. 4.57.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-react` to version `7.25.1`

eslint-config-seekingalpha-react ver. 4.76.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-react` to version `7.25.2`
- [deps] upgrade `eslint-plugin-flowtype` to version `6.0.1`
- [deps] upgrade `eslint-plugin-jest` to version `24.4.2`

eslint-config-seekingalpha-react ver. 4.78.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-jest` to version `24.5.2`

eslint-config-seekingalpha-react ver. 4.81.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-jest` to version `25.3.0`

eslint-config-seekingalpha-react ver. 4.93.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json

- [deps] update `eslint-plugin-promise` to version `5.2.0`

eslint-config-seekingalpha-base ver. 4.66.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-react` to version `7.28.0`

eslint-config-seekingalpha-react ver. 5.1.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json

- [deps] update `eslint-plugin-import` to version `2.25.4`

eslint-config-seekingalpha-base ver. 5.2.2

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/index.js
eslint-configs/eslint-config-seekingalpha-tests/package.json
eslint-configs/eslint-config-seekingalpha-tests/rules/eslint-plugin-testing-library/index.js

- [deps] integrate `eslint-plugin-testing-library`

eslint-config-seekingalpha-tests ver. 0.2.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json

- [deps] upgrade `eslint-plugin-testing-library` to version `5.0.4`

eslint-config-seekingalpha-tests ver. 0.3.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json
eslint-configs/eslint-config-seekingalpha-tests/rules/eslint-plugin-jest/index.js

eslint-config-seekingalpha-tests ver. 0.4.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json

- [deps] upgrade `eslint-plugin-testing-library` to version `5.0.5`

eslint-config-seekingalpha-tests ver. 1.0.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json
eslint-configs/eslint-config-seekingalpha-tests/rules/eslint-plugin-jest/index.js
eslint-configs/eslint-config-seekingalpha-tests/rules/eslint-plugin-testing-library/index.js

- [deps] upgrade `eslint-plugin-jest` to version `26.1.0`

eslint-config-seekingalpha-tests ver. 1.1.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/package.json
eslint-configs/eslint-config-seekingalpha-tests/rules/eslint-plugin-testing-library/index.js

- [deps] more `eslint-plugin-testing-library` rules

eslint-config-seekingalpha-tests ver. 1.2.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-unicorn/index.js

- [deps] update `eslint-plugin-unicorn` to version `41.0.0`
- [breaking] enable `unicorn/text-encoding-identifier-case` rule

eslint-config-seekingalpha-base ver. 5.6.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-react` to version `7.29.4`

eslint-config-seekingalpha-react ver. 5.11.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-react-hooks` to version `4.5.0`

eslint-config-seekingalpha-react ver. 5.16.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json

- [deps] upgrade `eslint-plugin-testing-library` to version `5.5.0`
- [deps] upgrade `eslint-plugin-jest` to version `26.2.2`

eslint-config-seekingalpha-tests ver. 1.15.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json
eslint-configs/eslint-config-seekingalpha-react/rules/eslint-plugin-react/jsx.js

- [deps] upgrade `eslint-plugin-react` to version `7.30.0`
- [breaking] enable `react/jsx-no-leaked-render` rule

eslint-config-seekingalpha-react ver. 5.18.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json

- [deps] upgrade `eslint-plugin-testing-library` to version `5.5.1`

eslint-config-seekingalpha-tests ver. 1.17.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json

- [deps] upgrade `eslint-plugin-jest` to version `26.4.5`

eslint-config-seekingalpha-tests ver. 1.19.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json

- [deps] upgrade `eslint-plugin-jest` to version `26.4.6`

eslint-config-seekingalpha-tests ver. 1.20.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-react` to version `7.30.1`
- [deps] upgrade `eslint-plugin-jsx-a11y` to version `6.6.0`

eslint-config-seekingalpha-react ver. 5.23.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json

- [deps] update `eslint-plugin-unicorn` to version `43.0.1`

eslint-config-seekingalpha-base ver. 5.20.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-jsx-a11y` to version `6.6.1`

eslint-config-seekingalpha-react ver. 5.26.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json

- [deps] upgrade `eslint-plugin-jest` to version `26.8.2`

eslint-config-seekingalpha-tests ver. 1.29.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json

- [deps] upgrade `eslint-plugin-jest` to version `26.8.3`

eslint-config-seekingalpha-tests ver. 1.31.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json

- [deps] upgrade `eslint-plugin-jest` to version `26.8.4`

eslint-config-seekingalpha-tests ver. 1.32.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json

- [deps] upgrade `eslint-plugin-jest` to version `26.8.5`

eslint-config-seekingalpha-tests ver. 1.33.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json

- [deps] upgrade `eslint-plugin-jest` to version `26.8.7`

eslint-config-seekingalpha-tests ver. 1.34.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-import/style-guide.js

- [breaking] enable `import/no-default-export` rule
- [breaking] enable `import/no-anonymous-default-export` rule

eslint-config-seekingalpha-base ver. 5.29.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.47.0`

eslint-config-seekingalpha-typescript ver. 1.5.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-react` to version `7.32.2`

eslint-config-seekingalpha-react ver. 6.6.1

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.51.0`

eslint-config-seekingalpha-typescript ver. 1.13.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json

- [deps] upgrade `eslint-plugin-testing-library` to version `5.10.1`

eslint-config-seekingalpha-tests ver. 1.53.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.52.0`

eslint-config-seekingalpha-typescript ver. 1.15.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json

- [deps] upgrade `eslint-plugin-testing-library` to version `5.10.2`

eslint-config-seekingalpha-tests ver. 1.55.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
eslint-configs/eslint-config-seekingalpha-typescript/rules/typescript-eslint/index.js

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.53.0`

eslint-config-seekingalpha-typescript ver. 1.16.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.54.0`

eslint-config-seekingalpha-typescript ver. 1.18.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json

- [deps] update `eslint-plugin-unicorn` to version `46.0.0`

eslint-config-seekingalpha-base ver. 5.49.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.54.1`

eslint-config-seekingalpha-typescript ver. 1.19.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.59.0`

eslint-config-seekingalpha-typescript ver. 2.3.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.59.1`

eslint-config-seekingalpha-typescript ver. 2.5.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.59.1`

eslint-config-seekingalpha-typescript ver. 2.5.1

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json

- [deps] upgrade `eslint-plugin-testing-library` to version `5.11.0`

eslint-config-seekingalpha-tests ver. 1.64.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-unicorn/index.js

- [breaking] enable `unicorn/prefer-string-replace-all` rule

eslint-config-seekingalpha-base ver. 6.6.1

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-unicorn/index.js

- [breaking] disable `unicorn/prefer-at` rule

eslint-config-seekingalpha-base ver. 6.6.3

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.59.6`

eslint-config-seekingalpha-typescript ver. 2.9.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.59.7`

eslint-config-seekingalpha-typescript ver. 2.11.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.59.8`

eslint-config-seekingalpha-typescript ver. 2.12.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.59.11`

eslint-config-seekingalpha-typescript ver. 2.14.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.60.1`

eslint-config-seekingalpha-typescript ver. 2.17.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `5.61.0`

eslint-config-seekingalpha-typescript ver. 2.19.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
eslint-configs/eslint-config-seekingalpha-typescript/rules/disable-recommended-eslint-rules/index.js

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `6.0.0`

eslint-config-seekingalpha-typescript ver. 3.0.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json

- [deps] upgrade `eslint-plugin-jest` to version `27.2.3`

eslint-config-seekingalpha-tests ver. 1.70.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-react` to version `7.33.0`

eslint-config-seekingalpha-react ver. 7.9.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/index.js
eslint-configs/eslint-config-seekingalpha-base/package.json

- [deps] update `eslint-plugin-unicorn` to version `48.0.1`

eslint-config-seekingalpha-base ver. 6.13.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json

- [deps] update `eslint-plugin-import` to version `2.28.0`

eslint-config-seekingalpha-base ver. 6.14.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json

- [deps] upgrade `eslint-plugin-react` to version `7.33.1`

eslint-config-seekingalpha-react ver. 7.12.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `6.2.1`

eslint-config-seekingalpha-typescript ver. 3.6.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `6.4.0`

eslint-config-seekingalpha-typescript ver. 3.10.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json

- [deps] update `eslint-plugin-import` to version `2.28.1`

eslint-config-seekingalpha-base ver. 6.19.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `6.5.0`

eslint-config-seekingalpha-typescript ver. 3.12.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `6.7.0`

eslint-config-seekingalpha-typescript ver. 3.15.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json

- [deps] update `eslint-plugin-array-func` to version `4.0.8`

eslint-config-seekingalpha-base ver. 6.22.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `6.7.2`

eslint-config-seekingalpha-typescript ver. 3.16.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json

- [deps] upgrade `eslint-plugin-jest` to version `27.4.2`

eslint-config-seekingalpha-tests ver. 1.79.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] fixed peerDependencies

eslint-config-seekingalpha-typescript ver. 3.18.1

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
eslint-configs/eslint-config-seekingalpha-typescript/rules/disable-recommended-eslint-rules/index.js
eslint-configs/eslint-config-seekingalpha-typescript/rules/typescript-eslint/index.js

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `6.8.0`

eslint-config-seekingalpha-typescript ver. 3.20.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
eslint-configs/eslint-config-seekingalpha-typescript/rules/typescript-eslint/index.js
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `6.15.0`
- [deps] upgrade `@typescript-eslint/parser` to version `6.15.0`

eslint-config-seekingalpha-typescript ver. 4.12.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-unicorn/index.js

- [deps] update `eslint-plugin-unicorn` to version `50.0.1`
- [breaking] enable `unicorn/no-unnecessary-polyfills` rule

eslint-config-seekingalpha-base ver. 7.10.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `6.16.0`
- [deps] upgrade `@typescript-eslint/parser` to version `6.16.0`

eslint-config-seekingalpha-typescript ver. 4.13.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `6.18.0`
- [deps] upgrade `@typescript-eslint/parser` to version `6.18.0`

eslint-config-seekingalpha-typescript ver. 4.16.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `6.18.1`
- [deps] upgrade `@typescript-eslint/parser` to version `6.18.1`

eslint-config-seekingalpha-typescript ver. 4.17.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
eslint-configs/eslint-config-seekingalpha-typescript/rules/typescript-eslint/index.js
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `6.19.0`
- [deps] upgrade `@typescript-eslint/parser` to version `6.19.0`

eslint-config-seekingalpha-typescript ver. 4.18.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/package.json
package.json

- [deps] update `eslint-plugin-unicorn` to version `51.0.0`

eslint-config-seekingalpha-base ver. 7.13.1

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
eslint-configs/eslint-config-seekingalpha-typescript/rules/typescript-eslint/index.js
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `7.1.0`
- [deps] upgrade `@typescript-eslint/parser` to version `7.1.0`

eslint-config-seekingalpha-typescript ver. 4.27.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json
package.json

- [deps] upgrade `eslint-plugin-react` to version `7.34.0`

eslint-config-seekingalpha-react ver. 7.26.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `7.1.1`
- [deps] upgrade `@typescript-eslint/parser` to version `7.1.1`

eslint-config-seekingalpha-typescript ver. 4.29.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `7.2.0`
- [deps] upgrade `@typescript-eslint/parser` to version `7.2.0`

eslint-config-seekingalpha-typescript ver. 4.30.1

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
eslint-configs/eslint-config-seekingalpha-typescript/rules/typescript-eslint/index.js
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `7.3.1`
- [deps] upgrade `@typescript-eslint/parser` to version `7.3.1`

eslint-config-seekingalpha-typescript ver. 4.32.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
eslint-configs/eslint-config-seekingalpha-typescript/rules/disable-recommended-eslint-rules/index.js
eslint-configs/eslint-config-seekingalpha-typescript/rules/typescript-eslint/index.js
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `7.4.0`
- [deps] upgrade `@typescript-eslint/parser` to version `7.4.0`

eslint-config-seekingalpha-typescript ver. 4.33.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `7.5.0`
- [deps] upgrade `@typescript-eslint/parser` to version `7.5.0`

eslint-config-seekingalpha-typescript ver. 4.34.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json
eslint-configs/eslint-config-seekingalpha-tests/rules/eslint-plugin-jest/index.js
package.json

- [deps] upgrade `eslint-plugin-jest` to version `28.2.0`

eslint-config-seekingalpha-tests ver. 1.95.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `7.8.0`
- [deps] upgrade `@typescript-eslint/parser` to version `7.8.0`

eslint-config-seekingalpha-typescript ver. 5.3.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json
package.json

- [deps] upgrade `eslint-plugin-jest` to version `28.5.0`

eslint-config-seekingalpha-tests ver. 1.98.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-unicorn/index.js
package.json

- [deps] update `eslint-plugin-unicorn` to version `53.0.0`
- [breaking] enable `unicorn/consistent-empty-array-spread` rule
- [breaking] enable `unicorn/no-invalid-fetch-options` rule
- [breaking] enable `unicorn/no-magic-array-flat-depth` rule
- [breaking] enable `unicorn/prefer-string-raw` rule
- [breaking] enable `unicorn/prefer-structured-clone` rule

eslint-config-seekingalpha-base ver. 8.1.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `7.9.0`
- [deps] upgrade `@typescript-eslint/parser` to version `7.9.0`

eslint-config-seekingalpha-typescript ver. 5.4.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `7.10.0`
- [deps] upgrade `@typescript-eslint/parser` to version `7.10.0`

eslint-config-seekingalpha-typescript ver. 5.5.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json
eslint-configs/eslint-config-seekingalpha-base/rules/eslint-plugin-unicorn/index.js
package.json

- [deps] update `eslint-plugin-unicorn` to version `53.0.0`
- [breaking] enable `unicorn/no-negation-in-equality-check` rule

eslint-config-seekingalpha-base ver. 8.5.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `7.14.1`
- [deps] upgrade `@typescript-eslint/parser` to version `7.14.1`

eslint-config-seekingalpha-typescript ver. 5.10.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json
package.json

- [deps] update `eslint-plugin-promise` to version `6.4.0`

eslint-config-seekingalpha-base ver. 8.6.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `7.15.0`
- [deps] upgrade `@typescript-eslint/parser` to version `7.15.0`

eslint-config-seekingalpha-typescript ver. 5.11.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `7.18.0`
- [deps] upgrade `@typescript-eslint/parser` to version `7.18.0`

eslint-config-seekingalpha-typescript ver. 5.15.0

---

eslint-configs/eslint-config-seekingalpha-tests/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-tests/README.md
eslint-configs/eslint-config-seekingalpha-tests/package.json
package.json

- [deps] upgrade `eslint-plugin-jest` to version `28.7.0`

eslint-config-seekingalpha-tests ver. 1.100.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `8.0.1`
- [deps] upgrade `@typescript-eslint/parser` to version `8.0.1`

eslint-config-seekingalpha-typescript ver. 5.17.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `8.2.0`
- [deps] upgrade `@typescript-eslint/parser` to version `8.2.0`

eslint-config-seekingalpha-typescript ver. 5.19.0

---

eslint-configs/eslint-config-seekingalpha-base/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-base/README.md
eslint-configs/eslint-config-seekingalpha-base/package.json

- [deps] update `eslint-plugin-import` to version `2.30.0`

eslint-config-seekingalpha-base ver. 8.11.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json
package.json

- [deps] upgrade `eslint-plugin-react` to version `7.35.2`
- [deps] upgrade `eslint-plugin-jsx-a11y` to version `6.10.0`

eslint-config-seekingalpha-react ver. 7.36.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json
package.json

- [deps] upgrade `eslint-plugin-react` to version `7.36.0`

eslint-config-seekingalpha-react ver. 7.37.0

---

eslint-configs/eslint-config-seekingalpha-react/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-react/README.md
eslint-configs/eslint-config-seekingalpha-react/package.json
package.json

- [deps] upgrade `eslint-plugin-react` to version `7.36.1`

eslint-config-seekingalpha-react ver. 7.38.0

---

eslint-configs/eslint-config-seekingalpha-typescript/CHANGELOG.md
eslint-configs/eslint-config-seekingalpha-typescript/README.md
eslint-configs/eslint-config-seekingalpha-typescript/package.json
package.json

- [deps] upgrade `@typescript-eslint/eslint-plugin` to version `8.6.0`
- [deps] upgrade `@typescript-eslint/parser` to version `8.6.0`

eslint-config-seekingalpha-typescript ver. 5.23.0
